# Generated by Django 3.1.7 on 2021-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allergies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='additional_notes',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='symptoms',
            field=models.TextField(max_length=200),
        ),
    ]
