# Generated by Django 3.2 on 2021-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_auto_20210416_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='repeat_unit',
            field=models.CharField(blank=True, choices=[('day(s)', 'Day'), ('week(s)', 'Week'), ('month(s)', 'Month'), ('hour(s)', 'Hour'), ('year(s)', 'Year'), ('other', 'Other')], default='day', max_length=100),
        ),
    ]
