# Generated by Django 3.2 on 2021-04-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0003_auto_20210417_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='repeat_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('hour', 'Hour'), ('year', 'Year'), ('other', 'Other')], default='day', max_length=100),
        ),
    ]
