# Generated by Django 3.2 on 2021-04-16 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=100)),
                ('ailment_type', models.CharField(choices=[('eye', 'Eye'), ('ear', 'Ear'), ('skin', 'Skin'), ('kidney', 'Kidney'), ('heart', 'Heart'), ('other', 'Other')], default='other', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.record')),
            ],
        ),
    ]
