# Generated by Django 3.2 on 2021-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ailment_type',
            field=models.CharField(max_length=100),
        ),
    ]
